[package]
name = "intcode_interpreter"
version = "0.1.0"
authors = ["mowzhja <mowzhja@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 2

[dependencies]
